version: "3.5"

name: caf

services:
  postgres:
    image: hub.docker.iec.io/library/postgres:11
    environment:
      - POSTGRES_DB=caf-server
      - POSTGRES_USER=caf-server
      - POSTGRES_PASSWORD=caf-server
    ports:
      - "5432:5432"

  redis:
    image: hub.docker.iec.io/library/redis:6
    ports:
      - "6379:6379"